- name: Build
  hosts: 127.0.0.1
  tasks:
    - name: Clean
      ansible.builtin.file:
        path: '{{ playbook_dir }}/build/'
        state: absent
    - name: Configure Directories
      ansible.builtin.file:
        path: '{{ playbook_dir }}/build/'
        state: directory
        mode: '755'
    - name: Configure Files
      ansible.builtin.file:
        path: '{{ playbook_dir }}/build/__init__.py'
        state: touch
        mode: '444'
    - name: Build Schemas
      changed_when: true
      ansible.builtin.command:
        chdir: '{{ playbook_dir }}'
        argv:
          - datamodel-codegen
          - --input=schemas/
          - --input-file-type=jsonschema
          - --output=build/schemas
          - --output-model-type=pydantic_v2.BaseModel
          - --use-annotated
          - --use-union-operator
          - --use-unique-items-as-set
          - --capitalize-enum-members
          - --use-exact-imports
          - --use-schema-description
          - --use-title-as-name
          - --use-double-quotes
